language: python
python: 3.3
env:
    - TOXENV=py33
    - TOXENV=py34
install:
    - pip install tox coveralls
    - python setup.py install
script: tox
after_success:
    # upload coverage data to coveralls.io
    - pushd .tox/${TOXENV}/lib/python*/site-packages
    - coveralls
    - popd
