language: python
python:
    - 3.4
    - 3.5
    - 3.6
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox coveralls
script: tox -e travis
after_success:
    # upload coverage data
    - coveralls
