language: python
python:
    - 3.4
    - 3.5
matrix:
  fast_finish: true
  allow_failures:
    - python: nightly
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox coveralls
script: tox -e travis
after_success:
    # upload coverage data
    - coveralls
