dist: xenial
language: python
python:
  - 3.6
  - 3.7
sudo: false
cache:
  pip: true
install:
  - pip install --upgrade pip
  - pip install tox coveralls
script: tox -e travis
after_success:
  # upload coverage data
  - coveralls
