language: python
python:
    - 3.3
    - 3.4
    - 3.5-dev
matrix:
  fast_finish: true
  allow_failures:
    - python: 3.5-dev
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
install: pip install 'tox<2' 'coveralls>=0.5'
script: tox -e travis
after_success:
    # upload coverage data
    - coveralls
