language: python
python: 3.3
env:
    - TOXENV=py33
    - TOXENV=py34
install:
    - pip install tox coveralls
    - python setup.py install
script: tox -e travis
after_success:
    # upload coverage data
    - coveralls
