name: Run tests

on:
  push:
    branches-ignore: [deploy]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Configure pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip coverage
        pip install pytest

    - name: Test with pytest
      run: |
        coverage run -p setup.py test

    - name: Report code coverage
      run: |
        coverage combine
        coverage report
        coverage xml

    - name: Submit code coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
